import type { NextPage } from 'next'
import Head from 'next/head'
import React from 'react'
import { BusTimes } from '../src/components/BusTimes'
import { QoTD } from '../src/components/QoTD'
import { Weather } from '../src/components/Weather'
import styles from '../styles/Home.module.css'
// import '../styles/App.css'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="App">
      <BusTimes />
      <div className="bottom-section">
       <Weather />
        <QoTD />
      </div>
    </div>
    </>
  )
}

export default Home
